# title of website
title: 程序员陈师兄

# description of website
description: cxy-csx's navigation site

# favicon of website
favicon: "https://github.com/cxy-csx.png?size=40"

# your website url
url: https://cxy-csx.github.io/nav/

# github profile url
github: "https://github.com/cxy-csx"

# footer message
footer: © 2021-2021 @cxy-csx

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: VPN节点
      sites:
        - name: 梯子代理
          description: 节点
          url: https://okzz.net/index.php#/register?code=raITdGfN
    - name: 云服务器
      sites:
        - name: 狗云
          description: 服务器
          url: https://www.dogyun.com/?ref=cxycsx
    - name: 技术文档
      sites:
        - name: Fluid
          description: Fluid主题
          url: https://hexo.fluid-dev.com/docs/start/
        - name: Wechatpy
          description: 微信开发文档
          url: https://www.wechatpy.org/
        - name: Mysql
          description: mysql开发文档
          url: https://dev.mysql.com/doc/refman/5.7/en/limit-optimization.html
        - name: Clash
          description: clash配置
          url: https://docs.cfw.lbyczf.com/
        - name: MDN
          description: MDN技术文档
          url: https://developer.mozilla.org/zh-CN/docs/Learn
        - name: Sa-Token
          description: sa-token开发文档
          url: https://sa-token.cc/
        - name: Spring File Storage
          description: 文件存储
          url: https://spring-file-storage.xuyanwu.cn/#/
        - name: Forset
          description: Http声明式客户端
          url: https://github.com/dromara/forest
        - name: OAuth
          description: 第三方登录
          url: https://www.justauth.cn/
        - name: React
          description: React官方文档
          url: https://zh-hans.react.dev/
        
    - name: 第三方依赖
      sites:
        - name: maven
          description: maven仓库
          url: https://mvnrepository.com/
    - name: AI智能
      sites:
        - name: Codeformer
          description: 照片修复
          url: https://replicate.com/sczhou/codeformer
        - name: AI对话
          description: ai
          url: https://bito.ai/
    - name: 实用工具
      sites:
        - name: 百度网盘
          description: 不限速下载
          url: https://github.com/syhyz1990/baiduyun
        - name: 无限邮箱
          description: 邮箱
          url: https://www.2925.com/login/
        - name: 浏览器插件
          description: 插件
          url: https://extfans.com/
        - name: crul转python
          description: crul
          url: https://curlconverter.com/
        - name: iTab标签
          description: iTab
          url: https://itab.link/
    - name: 账号密码
      sites:
        - name: Oracle账号
          description: orcal
          url: https://bugmenot.com/view/oracle.com
    - name: 软件安装包
      sites:
        - name: Notepad--
          description: Notepad
          url: https://gitee.com/cxasm/notepad--

    
